In [1]:
import  pandas as pd
df = pd.read_csv('data.csv')
df.head(10)

,Brand,Series,Version,Max Tension,Technologies,Origin,Price
0,Yonex,Arcsaber 0 Clear,NaN,30 lbs,"ISOMETRIC, AERO-BOX FRAME, BUILT-IN T-JOINT",Japan,579000
1,Yonex,Arcsaber 11,Pro,28 lbs,"ULTRA PE FIBER, SUPER HMG, ISOMETRIC Plus, SUP...",Japan,5099000
2,Yonex,Arcsaber 2 Ability,NaN,30 lbs,"ISOMETRIC, AERO-BOX FRAME, SUPER SLIM SHAFT, C...",Japan,1259000
3,Yonex,Arcsaber 2 Clear,NaN,30 lbs,"ISOMETRIC, AERO-BOX FRAME, SUPER SLIM SHAFT, C...",Japan,1259000
4,Yonex,Arcsaber 2,Feel,30 lbs,"ISOMETRIC, AERO-BOX FRAME, SUPER SLIM SHAFT, C...",Japan,1259000
5,Yonex,Arcsaber 7,Pro,27 lbs,"ULTRA PE FIBER, ISOMETRIC Plus, SUPER SLIM SHA...",Japan,4709000
6,Yonex,Astrox 01A 2024,NaN,28 lbs,"ISOMETRIC, AERO-BOX FRAME, SLIM SHAFT, ROTATIO...",Japan,1009000
7,Yonex,Astrox 01C 2024,NaN,28 lbs,"ISOMETRIC, AERO-BOX FRAME, SLIM SHAFT, ROTATIO...",Japan,1009000
8,Yonex,Astrox 01F 2024,NaN,28 lbs,"ISOMETRIC, AERO-BOX FRAME, SLIM SHAFT, ROTATIO...",Japan,1009000
9,Yonex,Astrox 10 DG (NV/TQ),NaN,NaN,"NANOMESH NEO, ISOMETRIC, AERO-BOX FRAME, ROTAT...",Japan,1940000

In [2]:
df['Brand'].value_counts()

Brand
Yonex     492
Victor    313
Lining    262
Name: count, dtype: int64

In [3]:
df['Max Tension'].value_counts()

Max Tension
26 lbs    176
30 lbs    153
24 lbs    135
28 lbs    135
29 lbs     74
32 lbs     56
27 lbs     53
31 lbs     28
35 lbs     21
25 lbs     13
22 lbs     12
23 lbs      9
33 lbs      9
18 lbs      9
34 lbs      4
20 lbs      3
21 lbs      1
36 lbs      1
Name: count, dtype: int64

In [ ]:

df['Series'].value_counts()

# khoang moi brand 2 sesi

Series
Astrox           10
Arcsaber         10
Astrox 99        10
Astrox 88D       10
Nanoray           9
                 ..
Voltric 80        1
Voltric 9 NEO     1
Voltric 9         1
ARC 10 PG         1
Windstorm N60     1
Name: count, Length: 900, dtype: int64

In [6]:
high = df[df['Price'] > 3_000_000]
mid = df[(df['Price'] >= 1_500_000) & (df['Price'] <= 3_000_000)]
low = df[df['Price'] < 1_500_000]

print(f"=== Cao cấp {len(high)}  ===")
print(high.groupby('Brand')['Series'].count())
print(f"\n=== Trung cấp {len(mid)} ===")
print(mid.groupby('Brand')['Series'].count())
print(f"\n=== Phổ thông : {len(low)} ===")
print(low.groupby('Brand')['Series'].count())

=== Cao cấp 240  ===
Brand
Lining    71
Victor    72
Yonex     97
Name: Series, dtype: int64

=== Trung cấp 395 ===
Brand
Lining     90
Victor    123
Yonex     181
Name: Series, dtype: int64

=== Phổ thông : 432 ===
Brand
Lining     97
Victor    116
Yonex     213
Name: Series, dtype: int64

In [9]:
for label, group in [("Cao cấp ", high)]:
    print(f"\n{'='*50}")
    print(f"{label}: {len(group)} sản phẩm")
    print('='*50)
    print(group[['Brand', 'Series', 'Version', 'Price']].to_string(index=False))

==================================================
Cao cấp : 240 sản phẩm
==================================================
 Brand                                                               Series                  Version    Price
 Yonex                                                          Arcsaber 11                      Pro  5099000
 Yonex                                                           Arcsaber 7                      Pro  4709000
 Yonex                                                           Astrox 100                  Tour VA  4469000
 Yonex                                                 Astrox 100ZZ Kurenai                      NaN  5429000
 Yonex                                                      Astrox 100ZZ VA                      NaN  5599000
 Yonex                                                            Astrox 77                      Pro  4349000
 Yonex                                                            Astrox 77                      Pro  4500000
 Yonex                                                           Astrox 88D                 Pro 2024  5039000
 Yonex                                                           Astrox 88D                      Pro  4039000
 Yonex                                                           Astrox 88S                 Pro 2024  5039000
 Yonex                                                            Astrox 99                      Pro  4719000
 Yonex                                                            Astrox 99                Tour 2025  4890000
 Yonex                                                      Nanoflare 1000Z                      NaN  5099000
 Yonex                                                        NanoFlare 800                      NaN  3479000
 Yonex                                                          Arcsaber 11                      Pro  5099000
 Yonex                                                       Astrox 70 (SA)                      NaN  4139000
 Yonex                                                            Astrox 77                      Pro  4349000
 Yonex                                                           Astrox 88D                Tour 2024  3099000
 Yonex                                                           Astrox 88S                Tour 2024  3099000
 Yonex                                                    Nanoflare 70 (RP)                      NaN  4139000
 Yonex                                                        Nanoflare 800                      Pro  5039000
 Yonex                                                          Arcsaber 11                     Tour  3349000
 Yonex                                                            Astrox 77     Pro Đỏ China Limited 13500000
 Yonex                                                            Astrox 77   Pro Xanh China Limited 13500000
 Yonex                                                            Astrox 99                     Tour  3579000
 Yonex                                                           Astrox 100                     Tour  4029000
 Yonex                                                         Astrox 22 RX                      NaN  3329000
 Yonex                                                            Astrox 99                 Pro 2025  5209000
 Yonex                                                          Arcsaber 11        Pro China Limited 13500000
 Yonex                                               Astrox 100ZZ Dark Navy                      NaN  4650000
 Yonex                                                 Astrox 100ZZ Kurenai                      NaN  4350000
 Yonex                                                           Astrox 88D                      Pro  4039000
 Yonex                                                            Astrox 99                      Pro  4190000
 Yonex                                                        NanoFlare 555                      NaN  4059000
 Yonex                                                   Nanoflare 700 Cyan                      NaN  3400000
 Yonex                                                    Nanoflare 700 Mag                      NaN  3400000
 Yonex                                                        Nanoflare 700                 Pro 2024  3850000
 Yonex                                                            Astrox 00                      NaN  3350000
 Yonex                                                   Astrox 100ZZ China                  Limited  8690000
 Yonex                                                           Astrox 55A                      NaN  3500000
 Yonex                                                       Nanoflare 1000                     Tour  3789000
 Yonex                                                         Nanoflare 70                      NaN  3650000
 Yonex                                                     NanoFlare 700 BP                      NaN  6900000
 Yonex                                                        Nanoflare 800                     Tour  3019000
 Yonex                                                         Nanoflare X7                      NaN  3009000
 Yonex                                                      Astrox 100ZZ BP                      NaN  6500000
 Yonex                                                           Astrox 88D              Pro Limited  5539000
 Yonex                                                           Astrox 88S              Pro Limited  6490000
 Yonex                                                        Nanoflare 400                      NaN  3050000
 Yonex                                                           Arcsaber 7                      Pro  4550000
 Yonex                                                         Astrox 77 Đỏ                      NaN  3220000
 Yonex                                                           Astrox 88S                      Pro  3979000
 Yonex                                                             Duora 10                      NaN  3340000
 Yonex                                                      Nanoflare 800LT                      NaN  3899000
 Yonex                                                      Arcsaber 11 new                      NaN  3190000
 Yonex                                   Astrox 99 sapphire navy (năm 2020)                      NaN  3320000
 Yonex                                                        NanoFlare 700       Limited - Dát Vàng  3380000
 Yonex                                                         Astrox 100ZZ                      NaN  3940000
 Yonex                                       Astrox 88S trắng đỏ (năm 2020)                      NaN  3110000
 Yonex                                                        Astrox 99 LCW                      NaN  3689000
 Yonex                                                        NanoFlare 600                      NaN  3190000
 Yonex                                                        NanoFlare 700                      NaN  3420000
 Yonex                                                        NanoFlare 700                      NaN  3420000
 Yonex                                                            Astrox 99                      NaN  3019000
 Yonex                                                    Duora 10 LCW 2016                      NaN  3339000
 Yonex                                                            Astrox 66                      NaN  3340000
 Yonex                                                            Duora 8XP                      NaN  3089000
 Yonex                                                          ARCSABER 11                      NaN  3239000
 Yonex                                                        Duora 10 2017                      NaN  3340000
 Yonex                                                    Duora 10 LCW 2017                      NaN  3090000
 Yonex                                                Duora 10 LCW RIO 2016                      NaN  4959000
 Yonex                                             Duora 10 (Legend Vision)                      NaN  3999000
 Yonex                                                        Nanoray 700FX                      NaN  3580000
 Yonex                                               Nanoray 900SE SETIAWAN                      NaN  3100000
 Yonex                                                        Voltric GlanZ                      NaN  3890000
 Yonex                                            VOLTRIC LD FORCE RIO 2016                      NaN  4669000
 Yonex                                                          ArcSaber FB                      NaN  3500000
 Yonex                                                 Nanoray Z-Speed 2016                      NaN  3190000
 Yonex                                                   Voltric Z Force II                      NaN  3470000
 Yonex                                                         ArcSaber 9FL                      NaN  4000000
 Yonex                                                     Nanoray 800 - JP                      NaN  4200000
 Yonex                                                        Nanoray GlanZ                      NaN  3079000
 Yonex                                                       Nanoray 700 RP                      NaN  3979000
 Yonex                                                       ArcSaber FB SP                      NaN  4319000
 Yonex                                                             Nano 500                      NaN  3479000
 Yonex                                                       NanoSpeed 6600                      NaN  3319000
 Yonex                                                            Nano 7700                      NaN  3479000
 Yonex                                                           Voltric 60                      NaN  3759000
 Yonex                                                           Voltric 80                      NaN  4199000
 Yonex                                                            ARC 10 PG                      NaN  4299000
 Yonex                                                        ARC Saber 3FL                      NaN  3269000
 Yonex                                                          ARC Saber 5                      NaN  3759000
 Yonex                                                        ARC Saber 5DX                      NaN  3729000
 Yonex                                                           ArcSaber 9                      NaN  3909000
 Yonex                                                         ArcSaber 9FL                      NaN  3969000
 Yonex                                                           AT 900 LCW                      NaN  4299000
 Yonex                                                           Voltric 70                      NaN  3809000
Victor                                                              ARS 90K                 Metallic  3400000
Victor                                          Auraspeed 100X Ultra G 2025                      NaN  3700000
Victor                                                  Auraspeed 90k II TD                      NaN  3100000
Victor                                              Auraspeed FANTÔME F HYQ                      NaN  4490000
Victor                                               Auraspeed Fantôme SC25                      NaN  4150000
Victor                                              DriveX 12 O Zheng Siwei                      NaN  3800000
Victor                                                       DriveX 12 WT25                      NaN  4449000
Victor                                                        DriveX 12 ZSW                      NaN  4490000
Victor                                                 Thruster F C Ultra X                      NaN  4200000
Victor                                                    Thruster Ryuga II                  Pro CPS  3950000
Victor                                                 Thruster Ryuga II TD                      NaN  3100000
Victor                                                       Thruster Ryuga             Metallic CPS  3950000
Victor                                                  Thruster Ryuga Muse                      NaN  3040000
Victor                               Thruster Shenron G – DragonBall Z 2025                      NaN  3200000
Victor                                                      TK - TTY Ultima                      NaN  3800000
Victor                                                         Auraspeed HS                     Plus  4950000
Victor                                                                 BS12                  SE 55TH  3399000
Victor                                                              Mjolnir    Metallic Limited 2024  3750000
Victor                                                             Ryuga II                      NaN  3850000
Victor                                                    Thruster Ryuga II                      Pro  3700000
Victor                                                           TK-F Ultra                      NaN  3400000
Victor                                                             ARS 100X                      NaN  3100000
Victor                                            Auraspeed 100X Ultra WT24                      NaN  3750000
Victor                                                 Auraspeed 100X Ultra                      NaN  3750000
Victor                                               Auraspeed FANTÔME 2025                      NaN  3450000
Victor                                          Auraspeed FANTÔME F AC 2025                      NaN  3750000
Victor                                                         Auraspeed HS                 Plus VBC  4190000
Victor                                                             Ryuga II      Pro China Open 2025  3950000
Victor                                                Thruster Ryuga Wukong                      NaN  3750000
Victor                                                            TK-FC LTD                      NaN  3900000
Victor                                                       ARS 100X Ultra                      NaN  4500000
Victor                                                Auraspeed 100X TUC/AC                      NaN  4900000
Victor                                                Auraspeed 100X TUC/AC                      NaN  3350000
Victor                                                       Brave Sword 12                      Pro  3200000
Victor                                                      Brave Sword LTD                      Pro  3900000
Victor                                                         Jetspeed S10                      NaN  3600000
Victor                                                                Ryuga Metallic China Open 2024  4400000
Victor                                                           Spider Man             Limited 2024  4990000
Victor                                                       Thruster Ryuga                 Metallic  3850000
Victor                                                             TK Ryuga            Metallic CO24  3700000
Victor                                                             TK-Ryuga                 Metallic  3500000
Victor                                                             ARS 100X                       SE  3100000
Victor                                                    Auraspeed 90F Tím                      NaN  3900000
Victor                                                      DX-10METALLIC B                      NaN  3830000
Victor                                                       Thruster Ryuga      Metallic China Open  5990000
Victor                                                           TK-Onigini                      NaN  3400000
Victor                                                    Hello Kitty TK-KT                      NaN  3250000
Victor                                                             ART - 98                      NaN  3300000
Victor                                                     Arrow Power 8800                      NaN  3510000
Victor                                                   SPIDER MAN LIMITED                      NaN  5100000
Victor                                                             TK 7000S                      New  3510000
Victor                                                               HX AIR                      NaN  3250000
Victor                                              Hypernano X 500 Control                      NaN  3300000
Victor                                          Hypernano X 800 LTD Control                      NaN  4190000
Victor                                            Hypernano X 800 LTD Power                      NaN  4190000
Victor Vợt Cầu lông JETSPEED 12 (JS 12) (Tặng vợt BRS011R + TK9 + Kawasiki)                      NaN  3940000
Victor                                                               JS BAO                      NaN  3600000
Victor                                                          JETSPEED S9                      NaN  3440000
Victor                                                      Thruster K7000L                      NaN  3450000
Victor                                                           TK ONIGIRI                      NaN  3300000
Victor                                                       HYPERNANO X800                      NaN  4190000
Victor                                           Vợt Cầu lông JETSPEED S 10                      NaN  3440000
Victor                                          Vợt Cầu lông JETSPEED S 8PS                      NaN  3390000
Victor                                                       JETSPEED S 8ST                      NaN  3390000
Victor                                      Vợt Cầu lông JETSPEED S AHMAD T                      NaN  3990000
Victor                                                  JETSPEED S NATSIR L                      NaN  3990000
Victor                                                      THRUSTER K 9000                      NaN  3740000
Victor                                                       Thruster K8000                      NaN  3050000
Victor                                                                MX 90                      NaN  3290000
Victor                                                           Iron Man 3                      NaN  5490000
Victor                                                      Auraspeed Punch                      NaN  4150000
Victor                                                Thruster K F C LTD GB                      NaN  6299000
Lining                                                       Aeronaut 7000B                      NaN  4050000
Lining                                                    Axforce 100 Gen 2                      NaN  5650000
Lining                                                           Axforce 80                    Light  4690000
Lining                                                           Axforce 80                      NaN  4320000
Lining                                                           Axforce 90  New - Loh Kean Yew 2025  5100000
Lining                                                           Bladex 700                      NaN  4400000
Lining                                                           Bladex 800                      NaN  4200000
Lining                                         Bladex 900 China Master 2025                      NaN  4850000
Lining                                                           Bladex 900                      NaN  4539000
Lining                                                         Calibar 900C                      NaN  4240000

In [12]:
df['Series'] = df['Series'].astype(str).str.split().str[0]
df.to_csv('dataprocessing.csv', index=False)
print("dataprocessing.csv")
df[['Brand', 'Series']].sort_values(['Brand', 'Series']).head(10)

dataprocessing.csv

      Brand Series
978  Lining  1210F
857  Lining     3D
858  Lining     3D
891  Lining     3D
892  Lining     3D
893  Lining     3D
939  Lining     3D
940  Lining     3D
979  Lining     3D
981  Lining     3D

In [ ]:
df = pd.read_csv('dataprocessing.csv')
df_grouped = df.groupby(['Brand', 'Series']).size().reset_index(name='Số lượng').sort_values(['Brand', 'Số lượng'], ascending=[True, False])

In [15]:
df_grouped.head(10)

     Brand     Series  Số lượng
62  Lining      Turbo        34
14  Lining   Aeronaut        23
18  Lining    Axforce        22
77  Lining  Windstorm        16
24  Lining    Calibar        12
21  Lining     Bladex        11
38  Lining  Halbertec        11
1   Lining         3D         9
60  Lining   Tectonic         9
74  Lining      Ultra         8

In [16]:
df = pd.read_csv('dataprocessing.csv')
df = df.sort_values(['Brand', 'Series', 'Price'], ascending=[True, True, True]).reset_index(drop=True)
df.to_csv('dataprocessing.csv', index=False)
print("Đã sắp xếp và lưu lại!")
df.head(20)

Đã sắp xếp và lưu lại!

,Brand,Series,Version,Max Tension,Technologies,Origin,Price
0,Lining,1210F,NaN,NaN,"TB NANO, AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME,...",China,1140000
1,Lining,3D,NaN,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,1150000
2,Lining,3D,NaN,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,1150000
3,Lining,3D,NaN,NaN,NaN,China,1205000
4,Lining,3D,NaN,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, ULTRA CA...",China,1450000
5,Lining,3D,NaN,26 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,1750000
6,Lining,3D,NaN,26 lbs,"BREAK FREE, HIGH TENSILE SLIM SHAFT, TB NANO, ...",China,1890000
7,Lining,3D,NaN,26 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2140000
8,Lining,3D,NaN,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,2289000
9,Lining,3D,NaN,32 lbs,"WING STABILIZER, 3D CALIBAR, STABILIZED ELASTI...",China,3900000
10,Lining,3G,NaN,NaN,"AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME",China,1730000
11,Lining,3G,NaN,26 lbs,"AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME",China,1840000
12,Lining,80,NaN,26 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2950000
13,Lining,90TD,NaN,28 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2590000
14,Lining,A1111,NaN,28 lbs,"TB-NANO, AEROTEC-BEAM",China,750000
15,Lining,A700,NaN,28 lbs,HIGH TENSILE SLIM SHAFT,China,900000
16,Lining,A762,NaN,22 lbs,"HDF, AEROTEC BEAM, AIR STREAM",China,800000
17,Lining,A800,NaN,28 lbs,HIGH TENSILE SLIM SHAFT,China,900000
18,Lining,A880,NaN,NaN,"HDF Shock Absorption System, AEROTEC BEAM, AIR...",China,800000
19,Lining,A880T,NaN,26 lbs,"HDF Shock Absorption System, AEROTEC BEAM",China,800000

In [17]:
df = pd.read_csv('dataprocessing.csv')

df['Version'] = df['Price'].apply(lambda x: 'v3' if x > 3_000_000 else ('v2' if x >= 1_500_000 else 'v1'))

df.to_csv('dataprocessing.csv', index=False)
print(df['Version'].value_counts())
df.head(20)

Version
v1    432
v2    395
v3    240
Name: count, dtype: int64

,Brand,Series,Version,Max Tension,Technologies,Origin,Price
0,Lining,1210F,v1,NaN,"TB NANO, AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME,...",China,1140000
1,Lining,3D,v1,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,1150000
2,Lining,3D,v1,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,1150000
3,Lining,3D,v1,NaN,NaN,China,1205000
4,Lining,3D,v1,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, ULTRA CA...",China,1450000
5,Lining,3D,v2,26 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,1750000
6,Lining,3D,v2,26 lbs,"BREAK FREE, HIGH TENSILE SLIM SHAFT, TB NANO, ...",China,1890000
7,Lining,3D,v2,26 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2140000
8,Lining,3D,v2,30 lbs,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,2289000
9,Lining,3D,v3,32 lbs,"WING STABILIZER, 3D CALIBAR, STABILIZED ELASTI...",China,3900000
10,Lining,3G,v2,NaN,"AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME",China,1730000
11,Lining,3G,v2,26 lbs,"AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME",China,1840000
12,Lining,80,v2,26 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2950000
13,Lining,90TD,v2,28 lbs,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2590000
14,Lining,A1111,v1,28 lbs,"TB-NANO, AEROTEC-BEAM",China,750000
15,Lining,A700,v1,28 lbs,HIGH TENSILE SLIM SHAFT,China,900000
16,Lining,A762,v1,22 lbs,"HDF, AEROTEC BEAM, AIR STREAM",China,800000
17,Lining,A800,v1,28 lbs,HIGH TENSILE SLIM SHAFT,China,900000
18,Lining,A880,v1,NaN,"HDF Shock Absorption System, AEROTEC BEAM, AIR...",China,800000
19,Lining,A880T,v1,26 lbs,"HDF Shock Absorption System, AEROTEC BEAM",China,800000

In [ ]:
df['Max Tension'] = df['Max Tension'].astype(str).str.replace(' lbs', '', regex=False)
df['Max Tension'] = pd.to_numeric(df['Max Tension'], errors='coerce')

print(f"Min: {df['Max Tension'].min()} lbs")
print(f"Max: {df['Max Tension'].max()} lbs")
print(f"Số dòng thiếu dữ liệu: {df['Max Tension'].isna().sum()}")
print()
df['Max Tension'].describe()

Min: 18.0 lbs
Max: 36.0 lbs
Số dòng thiếu dữ liệu: 175

count    892.000000
mean      27.652466
std        3.000237
min       18.000000
25%       26.000000
50%       28.000000
75%       30.000000
max       36.000000
Name: Max Tension, dtype: float64

In [19]:
df['Max Tension'] = df['Max Tension'].fillna(28)
df.to_csv('dataprocessing.csv', index=False)
print(f"Số NaN còn lại: {df['Max Tension'].isna().sum()}")
df['Max Tension'].describe()

Số NaN còn lại: 0

count    1067.000000
mean       27.709466
std         2.745956
min        18.000000
25%        26.000000
50%        28.000000
75%        30.000000
max        36.000000
Name: Max Tension, dtype: float64

In [22]:
df.head(20)

,Brand,Series,Version,Max Tension,Technologies,Origin,Price
0,Lining,1210F,v1,28.0,"TB NANO, AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME,...",China,1140000
1,Lining,3D,v1,30.0,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,1150000
2,Lining,3D,v1,30.0,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,1150000
3,Lining,3D,v1,28.0,NaN,China,1205000
4,Lining,3D,v1,30.0,"WING STABILIZER, 3D CALIBAR, TB NANO, ULTRA CA...",China,1450000
5,Lining,3D,v2,26.0,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,1750000
6,Lining,3D,v2,26.0,"BREAK FREE, HIGH TENSILE SLIM SHAFT, TB NANO, ...",China,1890000
7,Lining,3D,v2,26.0,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2140000
8,Lining,3D,v2,30.0,"WING STABILIZER, 3D CALIBAR, TB NANO, AEROTEC ...",China,2289000
9,Lining,3D,v3,32.0,"WING STABILIZER, 3D CALIBAR, STABILIZED ELASTI...",China,3900000
10,Lining,3G,v2,28.0,"AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME",China,1730000
11,Lining,3G,v2,26.0,"AEROTEC BEAM, DYNAMIN-OPT-IMUM FRAME",China,1840000
12,Lining,80,v2,26.0,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2950000
13,Lining,90TD,v2,28.0,"BREAK-FREE, UHB SHAFT, TB NANO, AEROTEC BEAM, ...",China,2590000
14,Lining,A1111,v1,28.0,"TB-NANO, AEROTEC-BEAM",China,750000
15,Lining,A700,v1,28.0,HIGH TENSILE SLIM SHAFT,China,900000
16,Lining,A762,v1,22.0,"HDF, AEROTEC BEAM, AIR STREAM",China,800000
17,Lining,A800,v1,28.0,HIGH TENSILE SLIM SHAFT,China,900000
18,Lining,A880,v1,28.0,"HDF Shock Absorption System, AEROTEC BEAM, AIR...",China,800000
19,Lining,A880T,v1,26.0,"HDF Shock Absorption System, AEROTEC BEAM",China,800000

In [24]:
all_techs = df['Technologies'].dropna().str.split(', ').explode().str.strip()
unique_techs = sorted(all_techs.unique())
print(f"Technologies : {len(unique_techs)}\n")
for i, tech in enumerate(unique_techs, 1):
    print(f"{i}. {tech}")

Technologies : 241

1. 3D CALIBAR
2. A CONCEPT
3. ACC-RIF TECH
4. AERO - BOX FRAME
5. AERO BOX FRAME
6. AERO DIAMOND
7. AERO DYNAMIC
8. AERO FRAME
9. AERO SWORD
10. AERO+BOX FRAME
11. AERO-BOX FRAME
12. AERO-BOX VARIFRAME
13. AERO-DIAMOND
14. AERO-HEX
15. AERO-SWORD
16. AERODYNAMIC FRAME CONSTRUCTION
17. AERONAUT TECHNOLOGY PLATFORM
18. AEROTEC BEAM
19. AEROTEC-BEAM
20. AEROTECH BEAM SYSTEM
21. AERRO DYNAMIC
22. AERRO-DIAMOND
23. AIR STREAM
24. AIR SYSTEM
25. ANTI TORQUE SPIRAL FRAME
26. ANTI-TORSION
27. ASSIST BUMPER
28. AXFORCE TECHNOLOGY
29. AXFORCE TECLONOGY
30. AXIMUM ENERGY TRANSFER
31. BIO INNER CONE
32. BIO-INNER-CONE
33. BLACK MICRO CORE
34. BOX FRAME
35. BOX SHAPE FRAME
36. BOX SHAPED FRAME
37. BOX WING FRAME
38. BREAK FREE
39. BREAK-FREE
40. BUILT-IN T-JOINT
41. CAPAULT STRUCTURE
42. CATAPULT STRUCTURE
43. CFR
44. COMPACT  FRAME
45. COMPACT FRAME
46. CONTROL SUPER CAP
47. CONTROL SUPPORT CAP
48. CONTROL- ASSIST BUMPER
49. CONTROL-ASSIST BUMPER
50. CSR
51. DF008- AERRO-DIAMOND
52. DF70- SEVEN-SIX76
53. DF90-TERS
54. DIAMOND
55. DOURA GROMMENT
56. DUAL OPTIMUM SYSTEM
57. DUAL WHIP-BACK SHAFT
58. DX- FRAME
59. DYNAMIC OPTIMUM FRAME
60. DYNAMIC-HEX
61. DYNAMIC-OPTIMUM FRAME
62. DYNAMIN-OPT-IMUM FRAME
63. DYNAMIN-OPTIMUM FRAME
64. ENERGY BOOST CAP
65. ENERGY BOOST CAP PLUS
66. ENERGY BOW
67. ENERGY BOW UPGRADE
68. ENHANCED ARCSABER FRAME
69. EX-HMG
70. EXPANDED SWEET SPOT FOR CONTROL
71. EXTRA SLIM SHAFT
72. FH- ISOMETRIC FRAME
73. FIBER REINFORCED SYSTEM
74. FLEXIBLE SHAFT
75. FORMTION
76. FREE CORE
77. FREE-CORE
78. FREECORE
79. FRS
80. FRTP TECH
81. FULL CONE
82. HARD CORE TECHNOLOGY
83. HARD CORED TECHNOLOGY
84. HDF
85. HDF Shock Absorption System
86. HIGH CARBON
87. HIGH MODULUS GRAPHITE
88. HIGH TENSILE SLIM SHAFT
89. HIGHT TENSILE SLIM SHAFT
90. HMR- SEVEN - SIX76
91. HORIZONTAL - A CONCEPT
92. HORIZONTAL-A CONCEPT
93. HOT MELT
94. HOT MET
95. HYBRID CN
96. I
SOMETRIC
97. IBUMPER
98. IC ELASTOMER
99. IMUM FRAME
100. IN T-JOINT
101. ISOMETRIC
102. ISOMETRIC HEAD FRAME
103. ISOMETRIC Plus
104. LIGHT FEEL CARBON NEO
105. LINING SUPER LIGHT TECHNOLOGY
106. LINING WOODS TECHNOLOGY PLATFORM
107. LOCKING CUBIC
108. M40
109. M40X
110. MAXIMUM ENERGY TRANSFER
111. METALLIC
112. METALLIC CARBON FIBER
113. MODULUS SLIM SHAFT
114. MPCF REINFORCING TECHNOLOGY
115. NAMD
116. NANO FORTIFY
117. NANO TEC
118. NANO TUBE
119. NANOAIR SPRING
120. NANOCELL
121. NANOCELL NEO
122. NANOMESH
123. NANOMESH NEO
124. NANOMETRIC
125. NANOSCIENCE
126. NANOTEC
127. NEO CS CARBON NANOTUBE
128. NEW AERO FRAME
129. NEW BIULT-IN T-JOINT
130. NEW BUIPLT-IN T-JOINT
131. NEW Built-in T-Joint
132. NEW EVOLUTION FRAME DESIGN-SIDE
133. NEW FRAME DESIGN AND RACQUET LENGTH
134. New GROMMET PATTERN
135. OCTABALDE
136. OPT-IMUM FRAME
137. OVAL HEAD
138. PBO HIGH PERFORMANCE FIBER
139. POCKETING BOOSTER
140. POWER ASSIST BUMPER
141. POWER BOOST CAP
142. POWER BOX
143. POWER FLEXIBLE SHAFT
144. POWER RING
145. POWER RING PRO
146. POWER-ASSIST BUMPER
147. POWERING PRO
148. POWERRING PRO
149. PYROFIL
150. PYROFL
151. RAZOR FRAME
152. REBOUND
153. REBOUND SHIELD
154. REBOUND TECHNOLOGY
155. REXIS SHAFT
156. ROTATIONAL GENARATOR SYSTEM
157. ROTATIONAL GENERATOR SYSTEM
158. SERVO FILTER
159. SEVEN - SIX76
160. SEVEN -SIX76
161. SEVEN SIX
162. SEVEN SIX -76
163. SEVEN SIX 76
164. SEVEN SIX-76
165. SEVEN-SIX
166. SEVEN-SIX 76
167. SEVEN-SIX76
168. SHARP WIND
169. SHOCK ABSORPTION SYSTEM
170. SHOCK ABSORTION SYSTEM
171. SIX 76
172. SLIM SHAFT
173. SOFT FLEXIBLE SHAFT
174. SOLIC FEEL CORE
175. SOLID FEEL CORE
176. SOLID FEEL CORE
177. SONIC BOOM SYSTEM
178. SONIC FLARE SYSTEM
179. SONIC METAL
180. SONIC-REBOUND
181. SONIC-REBOUND TECHNOLOGY
182. SOUND FILTER
183. SPEED- ASSIST BUMPER
184. STABILITY WEIGHT DISTRIBUTION
185. STABILIZED ELASTIC SHAFT
186. STABILIZED TORSION ANGLE
187. STABILIZED TORSSION ANGLE
188. SUPER HMG
189. SUPER LIGHT
190. SUPER SLIM FRAME
191. SUPER SLIM LONG SHAFT
192. SUPER SLIM SHAFT
193. SUPURB CARBON
194. SWING WEIGHT HEAD HEAVY
195. SWORD
196. Superb Carbon
197. T JOINT
198. T-ACHOR
199. T-ANCHOR
200. TB NANO
201. TB-NANO
202. TECTONIC TECHNOLOGY
203. TERS
204. TFA  CAP
205. TFA CAP PLUS
206. THUNDER TECHNOLOGY
207. TORAYCA M40X
208. TOUGHLEX
209. TRANS-WEIGHT SYSTEM
210. TRI- FORMATION
211. TRI-FORMATION
212. TRI-FORMTION
213. TRI-IBUMPER
214. TRI-VOLTAGE SYSTEM
215. TURBO CHARGING
216. TURBO NANO
217. TURBOCHARGING
218. Tungsten
219. UHB
220. UHB CARBON
221. UHB SHAFT
222. ULTRA CARBON
223. ULTRA PE FIBER
224. ULTRA PEF
225. ULTRA THIN FRAME
226. VDM
227. VERTICAL - A CONCEP
228. VIBRATION DAMPENING MESH
229. VIBRATION DAMPENING MESHL
230. VIBSLAYER CARBON
231. VOLTAGE SYSTEM
232. VOLUME CUT RESIN
233. WES
234. WES 2.0
235. WHIPPING
236. WHIPPING ENHANCE SYSTEM 2.0
237. WHIPPING ENHANCE SYSTEM 3.0
238. WING STABILIZER
239. WOVEN CARBON GRAPHITE
240. X-FULLERENE
241. XT- TRI-VOLTAGE SYSTEM

In [ ]:
df_orig = pd.read_csv('data.csv')

df_orig['Series'] = df_orig['Series'].astype(str).str.split().str[0]

frame_keywords = [
    'FRAME', 'ISOMETRIC', 'SWORD', 'BOX', 'DIAMOND', 'HEX', 'OCTABLADE',
    'FORMATION', 'COMPACT', 'RAZOR', 'THIN FRAME', 'GROMMET', 'BUMPER',
    'POWER RING', 'ENERGY BOW', 'SONIC FLARE', 'TRI-VOLTAGE', 'VOLTAGE',
    'CATAPULT', 'POCKETING'
]
material_keywords = [
    'NANO', 'CARBON', 'FIBER', 'TUNGSTEN', 'PYROFIL', 'HMG', 'M40X',
    'TORAYCA', 'FULLERENE', 'METALLIC', 'PBO', 'GRAPHITE', 'NAMD',
    'REXIS', 'NANOCELL', 'NEO CS'
]
stability_keywords = [
    'TORSION', 'JOINT', 'T-JOINT', 'ANCHOR', 'SHAFT', 'CORE', 'SYSTEM',
    'GENERATOR', 'ROTATIONAL', 'BOOST', 'CONTROL', 'VIBRATION', 'DAMPEN',
    'STABILIT', 'WES', 'CSR', 'CFR', 'FREECORE', 'FREE CORE', 'FREE-CORE',
    'REBOUND', 'WHIPPING', 'CAP', 'FILTER', 'SOUND'
]

def get_group_names(tech_str, keywords):
    if pd.isna(tech_str):
        return ''
    techs = [t.strip() for t in str(tech_str).split(',')]
    matched = [t for t in techs if any(kw.upper() in t.upper() for kw in keywords)]
    return ', '.join(matched) if matched else ''

df_orig['Tech_Frame'] = df_orig['Technologies'].apply(lambda x: get_group_names(x, frame_keywords))
df_orig['Tech_Material'] = df_orig['Technologies'].apply(lambda x: get_group_names(x, material_keywords))
df_orig['Tech_Stability'] = df_orig['Technologies'].apply(lambda x: get_group_names(x, stability_keywords))

df_orig['Version'] = df_orig['Price'].apply(lambda x: 'v3' if x > 3_000_000 else ('v2' if x >= 1_500_000 else 'v1'))

df_orig = df_orig.drop(columns=['Technologies'])
df_orig = df_orig.sort_values(['Brand', 'Series', 'Price']).reset_index(drop=True)

df_orig.to_csv('dataprocessing.csv', index=False)
print("Đã lưu!")
df_orig.head(10)

Đã lưu!

,Brand,Series,Version,Max Tension,Origin,Price,Tech_Frame,Tech_Material,Tech_Stability
0,Lining,1210F,v1,NaN,China,1140000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",AIR SYSTEM
1,Lining,3D,v1,30 lbs,China,1150000,DYNAMIN-OPTIMUM FRAME,"TB NANO, TURBO NANO",
2,Lining,3D,v1,30 lbs,China,1150000,DYNAMIN-OPTIMUM FRAME,"TB NANO, TURBO NANO, ULTRA CARBON",
3,Lining,3D,v1,NaN,China,1205000,,,
4,Lining,3D,v1,30 lbs,China,1450000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, ULTRA CARBON, TURBO NANO",
5,Lining,3D,v2,26 lbs,China,1750000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
6,Lining,3D,v2,26 lbs,China,1890000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",HIGH TENSILE SLIM SHAFT
7,Lining,3D,v2,26 lbs,China,2140000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
8,Lining,3D,v2,30 lbs,China,2289000,DYNAMIN-OPTIMUM FRAME,"TB NANO, TURBO NANO",
9,Lining,3D,v3,32 lbs,China,3900000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",STABILIZED ELASTIC SHAFT

In [28]:
df_orig.head(25)

,Brand,Series,Version,Max Tension,Origin,Price,Tech_Frame,Tech_Material,Tech_Stability
0,Lining,1210F,v1,NaN,China,1140000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",AIR SYSTEM
1,Lining,3D,v1,30 lbs,China,1150000,DYNAMIN-OPTIMUM FRAME,"TB NANO, TURBO NANO",
2,Lining,3D,v1,30 lbs,China,1150000,DYNAMIN-OPTIMUM FRAME,"TB NANO, TURBO NANO, ULTRA CARBON",
3,Lining,3D,v1,NaN,China,1205000,,,
4,Lining,3D,v1,30 lbs,China,1450000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, ULTRA CARBON, TURBO NANO",
5,Lining,3D,v2,26 lbs,China,1750000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
6,Lining,3D,v2,26 lbs,China,1890000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",HIGH TENSILE SLIM SHAFT
7,Lining,3D,v2,26 lbs,China,2140000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
8,Lining,3D,v2,30 lbs,China,2289000,DYNAMIN-OPTIMUM FRAME,"TB NANO, TURBO NANO",
9,Lining,3D,v3,32 lbs,China,3900000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",STABILIZED ELASTIC SHAFT
10,Lining,3G,v2,NaN,China,1730000,DYNAMIN-OPT-IMUM FRAME,,
11,Lining,3G,v2,26 lbs,China,1840000,DYNAMIN-OPT-IMUM FRAME,,
12,Lining,80,v2,26 lbs,China,2950000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
13,Lining,90TD,v2,28 lbs,China,2590000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
14,Lining,A1111,v1,28 lbs,China,750000,,TB-NANO,
15,Lining,A700,v1,28 lbs,China,900000,,,HIGH TENSILE SLIM SHAFT
16,Lining,A762,v1,22 lbs,China,800000,,,
17,Lining,A800,v1,28 lbs,China,900000,,,HIGH TENSILE SLIM SHAFT
18,Lining,A880,v1,NaN,China,800000,,,HDF Shock Absorption System
19,Lining,A880T,v1,26 lbs,China,800000,,,HDF Shock Absorption System
20,Lining,A900,v1,28 lbs,China,900000,,,HIGH TENSILE SLIM SHAFT
21,Lining,A900T,v1,28 lbs,China,900000,,,
22,Lining,AIR-STREAM,v3,30 lbs,China,3890000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO",UHB SHAFT
23,Lining,Aeronaut,v2,30 lbs,China,1590000,DYNAMIN-OPT-IMUM FRAME,ULTRA CARBON,"HIGH TENSILE SLIM SHAFT, AIR SYSTEM, SHOCK ABS..."
24,Lining,Aeronaut,v2,30 lbs,China,1890000,DYNAMIN-OPT-IMUM FRAME,"TB NANO, TURBO NANO","UHB SHAFT, STABILIZED ELASTIC SHAFT, AIR SYSTEM"